import { Suit } from "./Suit"

export interface Card {
  name: string
  value: number
  coldValue: number
  suit: Suit
  renegable: boolean
}

export interface SelectableCard extends Card {
  selected: boolean
}

export const BLANK_CARD: Card = {
  name: "blank_card",
  value: 0,
  coldValue: 0,
  suit: Suit.EMPTY,
  renegable: false,
}

export const CARDS: Card[] = [
  { name: "EMPTY", value: 0, coldValue: 0, suit: Suit.EMPTY, renegable: false },
  {
    name: "TWO_HEARTS",
    value: 101,
    coldValue: 2,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "THREE_HEARTS",
    value: 102,
    coldValue: 3,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "FOUR_HEARTS",
    value: 103,
    coldValue: 4,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "SIX_HEARTS",
    value: 104,
    coldValue: 6,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "SEVEN_HEARTS",
    value: 105,
    coldValue: 7,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "EIGHT_HEARTS",
    value: 106,
    coldValue: 8,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "NINE_HEARTS",
    value: 107,
    coldValue: 9,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "TEN_HEARTS",
    value: 108,
    coldValue: 10,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "QUEEN_HEARTS",
    value: 109,
    coldValue: 12,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "KING_HEARTS",
    value: 110,
    coldValue: 13,
    suit: Suit.HEARTS,
    renegable: false,
  },
  {
    name: "ACE_HEARTS",
    value: 112,
    coldValue: 0,
    suit: Suit.WILD,
    renegable: true,
  },
  {
    name: "JACK_HEARTS",
    value: 114,
    coldValue: 11,
    suit: Suit.HEARTS,
    renegable: true,
  },
  {
    name: "FIVE_HEARTS",
    value: 115,
    coldValue: 5,
    suit: Suit.HEARTS,
    renegable: true,
  },
  {
    name: "TWO_DIAMONDS",
    value: 101,
    coldValue: 2,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "THREE_DIAMONDS",
    value: 102,
    coldValue: 3,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "FOUR_DIAMONDS",
    value: 103,
    coldValue: 4,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "SIX_DIAMONDS",
    value: 104,
    coldValue: 6,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "SEVEN_DIAMONDS",
    value: 105,
    coldValue: 7,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "EIGHT_DIAMONDS",
    value: 106,
    coldValue: 8,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "NINE_DIAMONDS",
    value: 107,
    coldValue: 9,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "TEN_DIAMONDS",
    value: 108,
    coldValue: 10,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "QUEEN_DIAMONDS",
    value: 109,
    coldValue: 12,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "KING_DIAMONDS",
    value: 110,
    coldValue: 13,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "ACE_DIAMONDS",
    value: 111,
    coldValue: 1,
    suit: Suit.DIAMONDS,
    renegable: false,
  },
  {
    name: "JACK_DIAMONDS",
    value: 114,
    coldValue: 11,
    suit: Suit.DIAMONDS,
    renegable: true,
  },
  {
    name: "FIVE_DIAMONDS",
    value: 115,
    coldValue: 5,
    suit: Suit.DIAMONDS,
    renegable: true,
  },
  {
    name: "TEN_CLUBS",
    value: 101,
    coldValue: 1,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "NINE_CLUBS",
    value: 102,
    coldValue: 2,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "EIGHT_CLUBS",
    value: 103,
    coldValue: 3,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "SEVEN_CLUBS",
    value: 104,
    coldValue: 4,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "SIX_CLUBS",
    value: 105,
    coldValue: 5,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "FOUR_CLUBS",
    value: 106,
    coldValue: 7,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "THREE_CLUBS",
    value: 107,
    coldValue: 8,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "TWO_CLUBS",
    value: 108,
    coldValue: 9,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "QUEEN_CLUBS",
    value: 109,
    coldValue: 12,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "KING_CLUBS",
    value: 110,
    coldValue: 13,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "ACE_CLUBS",
    value: 111,
    coldValue: 10,
    suit: Suit.CLUBS,
    renegable: false,
  },
  {
    name: "JACK_CLUBS",
    value: 114,
    coldValue: 11,
    suit: Suit.CLUBS,
    renegable: true,
  },
  {
    name: "FIVE_CLUBS",
    value: 115,
    coldValue: 6,
    suit: Suit.CLUBS,
    renegable: true,
  },
  {
    name: "TEN_SPADES",
    value: 101,
    coldValue: 1,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "NINE_SPADES",
    value: 102,
    coldValue: 2,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "EIGHT_SPADES",
    value: 103,
    coldValue: 3,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "SEVEN_SPADES",
    value: 104,
    coldValue: 4,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "SIX_SPADES",
    value: 105,
    coldValue: 5,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "FOUR_SPADES",
    value: 106,
    coldValue: 7,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "THREE_SPADES",
    value: 107,
    coldValue: 8,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "TWO_SPADES",
    value: 108,
    coldValue: 9,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "QUEEN_SPADES",
    value: 109,
    coldValue: 12,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "KING_SPADES",
    value: 110,
    coldValue: 13,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "ACE_SPADES",
    value: 111,
    coldValue: 10,
    suit: Suit.SPADES,
    renegable: false,
  },
  {
    name: "JACK_SPADES",
    value: 114,
    coldValue: 11,
    suit: Suit.SPADES,
    renegable: true,
  },
  {
    name: "FIVE_SPADES",
    value: 115,
    coldValue: 6,
    suit: Suit.SPADES,
    renegable: true,
  },
  { name: "JOKER", value: 113, coldValue: 0, suit: Suit.WILD, renegable: true },
]
