name: Publish to Dockerhub

on:
    release:
        types: [published]

jobs:
    publish:
        name: Build and Publish docker image to dockerhub
        permissions:
            contents: write
            pull-requests: write
            packages: read
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Get version in manifest.json
              id: manifest-version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: "public/manifest.json"
                  prop_path: "version"
            - name: Ensure the manifest version matches the tag version
              if: ${{ steps.manifest-version.outputs.prop != github.ref_name }}
              uses: actions/github-script@v3
              with:
                  script: |
                      core.setFailed('The version in the manifest must match the tag.')
            - name: Get version in package.json
              id: package-version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: "package.json"
                  prop_path: "version"
            - name: Ensure the package.json version matches the tag version
              if: ${{ steps.package-version.outputs.prop != github.ref_name }}
              uses: actions/github-script@v3
              with:
                  script: |
                      core.setFailed('The version in the package.json must match the tag.')
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Publish to Dockerhub
              uses: elgohr/Publish-Docker-Github-Action@v5
              with:
                  name: daithihearn/cards-110-frontend
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  platforms: linux/amd64,linux/arm64/v8
                  tags: "latest, ${{ github.ref_name }}"
