name: CI

on:
    workflow_dispatch:
    pull_request:
        branches: ["main"]

jobs:
    unit-tests-and-coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.11.x"
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Test and coverage
              run: yarn jest --coverage
            - name: Sonar Args
              id: sonar-args
              run: |
                  if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
                    echo "SONAR_ARGS=-Dsonar.branch.name=main" >> $GITHUB_OUTPUT
                  else
                    echo "SONAR_ARGS=-Dsonar.branch.target=main -Dsonar.branch.name=${{ github.head_ref }}" >> $GITHUB_OUTPUT
                  fi

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: ${{ steps.sonar-args.outputs.SONAR_ARGS }}
